macro(get_install_destination)
	if(NOT INSTALL_DESTINATION)
		if(THIRD_PARTY_LIBS_DIR)
			set(INSTALL_DESTINATION THIRD_PARTY_LIBS_DIR)
		elseif(DEFINED ENV{THIRD_PARTY_LIBS_DIR})
			set(INSTALL_DESTINATION $ENV{THIRD_PARTY_LIBS_DIR})
		else()
			message(WARNING "Install destination not set. Using default install folder. Either set THIRD_PARTY_LIBS_DIR or INSTALL_DESTINATION to change the install path")
		endif()
	endif()
endmacro()